using UnityEngine;

/// <summary>
/// This script smoothly shifts the background color of the Camera continuously over time!
/// It creates a relaxing "Zen" atmosphere by slowly cross-fading through random pastel colors.
/// The [RequireComponent] attribute automatically forces the Camera component to exist on whatever object this script is put on!
/// </summary>
[RequireComponent(typeof(Camera))]
public class BackgroundColorCycler : MonoBehaviour
{
    [Tooltip("How fast the background transitions to the next color. A lower number means a slower, more relaxing fade.")]
    public float transitionSpeed = 0.5f;

    // A reference to the physical Camera on this object.
    private Camera cam;
    
    // The color we are currently shifting AWAY from.
    private Color startColor;
    
    // The new target color we are shifting TOWARDS.
    private Color endColor;
    
    // 't' is time. It acts as a percentage from 0f (0%) to 1f (100%) showing how close we are to the endColor.
    private float t = 0f;

    void Start()
    {
        // GetComponent automatically finds the physical Camera attached to this exact same GameObject.
        cam = GetComponent<Camera>();
        
        // This forces the Camera to draw the solid color background rather than a Skybox image!
        cam.clearFlags = CameraClearFlags.SolidColor;
        
        // Our starting point is whatever color you already set the camera to in the Inspector.
        startColor = cam.backgroundColor;
        
        // Our target point is a completely random bright pastel color generated by our helper method below!
        endColor = GetRandomPastelColor();
    }

    void Update()
    {
        // Time.deltaTime ensures the speed is constant regardless of whether the player's computer is running
        // at 30 frames per second or 144 frames per second!
        t += Time.deltaTime * transitionSpeed;

        // Color.Lerp mathematically blends two colors together. 
        // If 't' is 0.5f, it mixes them exactly 50/50! We apply this mixed color directly to the camera every frame.
        cam.backgroundColor = Color.Lerp(startColor, endColor, t);

        // When 't' reaches 1.0f (100%), the fade is totally complete. Time to pick a new color!
        if (t >= 1f)
        {
            // Reset the timer
            t = 0f;
            // Our old target color is now our starting point...
            startColor = endColor;
            // ... and we find a brand new target color to aim for!
            endColor = GetRandomPastelColor();
        }
    }

    /// <summary>
    /// Generates beautiful, relaxed pastel colors instead of ugly, harsh neon colors.
    /// </summary>
    private Color GetRandomPastelColor()
    {
        // Random.ColorHSV uses the "Hue, Saturation, Value" color wheel technique.
        // Hue is random from red to purple (0f - 1f).
        // Saturation (color intensity) is restricted to low-medium (0.2f - 0.4f) so it looks "pastel" and soft.
        // Value (brightness) is kept high (0.8f - 1f) so it's pleasant and bright, not muddy.
        return Random.ColorHSV(0f, 1f, 0.2f, 0.4f, 0.8f, 1f);
    }
}
